parameters:
    max.recent: 5 #количество ивентов выводимое в блоке Последние совершенные звонки/встречи
    count.days: 3 #количество дней, после которой заявка считаеться просроченной
    item_per_page: 15 #для пагинации
    event_delete_interval: P4D #количество дней после которого удаляется просроченное событие
    menu.config_name: menu.yml
#Repositories
    client.repository.customer.name: ClientBundle:Customer
    client.repository.call.name: ClientBundle:Call
    client.repository.meeting.name: ClientBundle:Meeting
#Forms
    client.form.customer.class: ClientBundle\Form\CustomerForm
    client.form.call.class: ClientBundle\Form\CallForm
    client.form.meeting.class: ClientBundle\Form\MeetingForm
#Filter forms
    client.filter.form.customer.class: ClientBundle\Filter\FormFilter\CustomerFilter
    client.filter.form.call.class: ClientBundle\Filter\FormFilter\EventFilter
    client.filter.form.meeting.class: ClientBundle\Filter\FormFilter\EventFilter
    client.filter.form.charts.class: ClientBundle\Filter\FormFilter\ChartsFilter
