parameters:
    max.recent: 5
    count.days: 3
#Repositories
    client.repository.customer.name: ClientBundle:Customer
    client.repository.call.name: ClientBundle:Call
    client.repository.meeting.name: ClientBundle:Meeting
#Forms
    client.form.customer.class: ClientBundle\Form\CustomerForm
    client.form.call.class: ClientBundle\Form\CallForm
    client.form.meeting.class: ClientBundle\Form\MeetingForm
#Filter forms
    client.filter.form.customer.class: ClientBundle\Filter\FormFilter\CustomerFilter
    client.filter.form.call.class: ClientBundle\Filter\FormFilter\EventFilter
    client.filter.form.meeting.class: ClientBundle\Filter\FormFilter\EventFilter
