client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Default:index }

client_customers:
    path: /customers
    defaults: {_controller: 'client.controller.customer:listAction'}

client_customer.add:
    path: /customer/add
    defaults: {_controller: 'client.controller.customer:createAction'}

client_customer.edit:
    path: /customer/{id}
    defaults: {_controller: 'client.controller.customer:updateAction'}
    requirements:
        id: \d+

client_customer.delete:
    path: /customer/{id}/delete
    defaults: {_controller: 'client.controller.customer:deleteAction'}
    requirements:
        id: \d+

client_calls:
    path: /customer/{id_customer}/calls
    defaults: {_controller: 'client.controller.call:listAction'}
    requirements:
        id_customer: \d+

client_call.add:
    path: /customer/{id_customer}/call/add
    defaults: {_controller: 'client.controller.call:createAction'}
    requirements:
        id_customer: \d+

client_call.status.active:
    path: /customer/{id_customer}/call/{id_event}/active
    defaults: {_controller: 'client.controller.call:activateStatusAction'}
    requirements:
        id_customer: \d+
        id_event: \d+

client_call.delete:
    path: /customer/{id_customer}/call/{id}/delete
    defaults: {_controller: 'client.controller.call:deleteAction'}
    requirements:
        id_customer: \d+
        id: \d+

client_call.today:
    path: /today/call
    defaults: {_controller: 'client.controller.call:getTodayAction'}

client_meetings:
    path: /customer/{id_customer}/meetings
    defaults: {_controller: 'client.controller.meeting:listAction'}
    requirements:
        id_customer: \d+

client_meeting.add:
    path: /customer/{id_customer}/meeting/add
    defaults: {_controller: 'client.controller.meeting:createAction'}
    requirements:
        id_customer: \d+

client_meeting.status.active:
    path: /customer/{id_customer}/meeting/{id_event}/active
    defaults: {_controller: 'client.controller.meeting:activateStatusAction'}
    requirements:
        id_customer: \d+
        id_event: \d+

client_meeting.delete:
    path: /customer/{id_customer}/meeting/{id}/delete
    defaults: {_controller: 'client.controller.meeting:deleteAction'}
    requirements:
        id_customer: \d+
        id: \d+

client_meeting.today:
    path: /today/meeting
    defaults: {_controller: 'client.controller.meeting:getTodayAction'}

client_calendar.show:
    path: /calendar
    defaults: {_controller: 'ClientBundle:Calendar:show'}

client_charts.call_pie:
    path: /charts/calls/pie
    defaults: {_controller: 'client.controller.charts_controller:pieAction', type: 'call'}

client_charts.meeting_pie:
    path: /charts/meetings/pie
    defaults: {_controller: 'client.controller.charts_controller:pieAction', type: 'meeting'}

client_charts.call_column:
    path: /charts/calls/{user_id}
    defaults: {_controller: 'client.controller.charts_controller:columnAction', type: 'call'}
    requirements:
        user_id: \d+