client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Default:index }

client_customers:
    path: /customers
    defaults: {_controller: 'client.controller.customer:listAction'}

client_customer.add:
    path: /customer/add
    defaults: {_controller: 'client.controller.customer:createAction'}

client_customer.edit:
    path: /customer/{id}
    defaults: {_controller: 'client.controller.customer:updateAction'}
    requirements:
        id: \d+

client_calls:
    path: /customer/{id_customer}/calls
    defaults: {_controller: 'client.controller.call:listAction'}
    requirements:
        id_customer: \d+

client_call.add:
    path: /customer/{id_customer}/call/add
    defaults: {_controller: 'client.controller.call:createAction'}
    requirements:
        id_customer: \d+

client_meeting.add:
    path: /customer/{id_customer}/meeting/add
    defaults: {_controller: 'client.controller.meeting:createAction'}
    requirements:
        id_customer: \d+
