client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Default:index }

client_customers:
    path: /customers
    defaults: {_controller: 'client.controller.customer:listAction'}

client_customer.add:
    path: /customer/add
    defaults: {_controller: 'client.controller.customer:createAction'}