services:
    client.entity.customer:
        class: ClientBundle\Entity\Customer

    client.entity.call:
        class: ClientBundle\Entity\Call

    client.entity.meeting:
        class: ClientBundle\Entity\Meeting
