services:
    client.filter.form.customer:
        class: ClientBundle\Filter\FormFilter\CustomerFilter
        arguments: ['@security.token_storage']
        tags:
            - {name: form.type, alias: customer_filter}

#Doctrine filter configurator
    client.doctrine.filter.configurator:
        class: ClientBundle\Filter\SQLFilter\Configurator
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@annotation_reader"]
        tags:
            - {name: kernel.event_listener, event: kernel.request}