services:
    client.calendar.call:
        class: ClientBundle\Listener\EventListener\CalendarCallEventListener
        arguments:
            - "@client.service.call"
        tags:
            - {name: kernel.event_listener, event: calendar.load_events, method: loadEvents}

    client.calendar.meeting:
        class: ClientBundle\Listener\EventListener\CalendarMeetingEventListener
        arguments:
            - "@client.service.meeting"
        tags:
            - {name: kernel.event_listener, event: calendar.load_events, method: loadEvents}