services:
    client.service.customer:
        class: ClientBundle\Service\FilterService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%client.repository.customer.name%"
            - "@lexik_form_filter.query_builder_updater"

    client.service.call:
        class: ClientBundle\Service\FilterService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%client.repository.call.name%"
            - "@lexik_form_filter.query_builder_updater"

    client.service.meeting:
        class: ClientBundle\Service\FilterService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%client.repository.meeting.name%"
            - "@lexik_form_filter.query_builder_updater"

    client.service.users:
        class: ClientBundle\Service\UsersService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%client.repository.user.name%"


