services:
#Controllers:
    client.controller.customer:
        class: ClientBundle\Controller\CustomerController
        arguments:
            - "@client.service.customer"
            - "%client.form.customer.class%"
            - "@client.entity.customer"
            - "@knp_paginator"
            - "%client.filter.form.customer.class%"
        calls:
            - [setContainer, ['@service_container']]

    client.controller.call:
        class: ClientBundle\Controller\CallController
        arguments:
            - "@client.service.call"
            - "%client.form.call.class%"
            - "@client.entity.call"
            - "@knp_paginator"
            - "%client.filter.form.call.class%"
        calls:
            - [setContainer, ['@service_container']]

    client.controller.meeting:
        class: ClientBundle\Controller\MeetingController
        arguments:
            - "@client.service.meeting"
            - "%client.form.meeting.class%"
            - "@client.entity.meeting"
            - "@knp_paginator"
            - "%client.filter.form.meeting.class%"
        calls:
            - [setContainer, ['@service_container']]
