services:
    client.security.base_voter:
        class: ClientBundle\Security\BaseVoter
        tags:
            - {name: security.voter}
        public: false

    client.security.user.delete_voter:
        class: ClientBundle\Security\UserManipulatorVoter
        tags:
            - {name: security.voter}
        public: false

    client.security.user.profile:
        class: ClientBundle\Security\UserProfileVoter
        tags:
            - {name: security.voter}
        public: false