services:
    client.listener.exception:
        class: ClientBundle\Listener\EventListener\ExceptionListener
        tags:
            - {name: kernel.event_listener, event: kernel.exception}

    client.listener.registration_subscriber:
        class: ClientBundle\Listener\EventSubscriber\RegistrationSubscriber
        arguments:
            - "@router"
        tags:
            - {name: kernel.event_subscriber}