services:
#Controllers:
    client.controller.customer:
        class: ClientBundle\Controller\CustomerController
        arguments:
            - "@client.service.customer"
            - "%client.form.customer.class%"
            - "@client.entity.customer"
            - "@knp_paginator"
        calls:
            - [setContainer, ['@service_container']]
            - [addFilterFormClass, [{name: list, class: "%client.filter.form.customer.class%"}]]

    client.controller.call:
        class: ClientBundle\Controller\CallController
        arguments:
            - "@client.service.call"
            - "%client.form.call.class%"
            - "@client.entity.call"
            - "@knp_paginator"
            - "%client.filter.form.call.class%"
        calls:
            - [setContainer, ['@service_container']]
            - [addFilterFormClass, [{name: list, class: "%client.filter.form.call.class%"}]]

    client.controller.meeting:
        class: ClientBundle\Controller\MeetingController
        arguments:
            - "@client.service.meeting"
            - "%client.form.meeting.class%"
            - "@client.entity.meeting"
            - "@knp_paginator"
        calls:
            - [setContainer, ['@service_container']]
            - [addFilterFormClass, [{name: list, class: "%client.filter.form.meeting.class%"}]]

    client.controller.charts_controller:
        class: ClientBundle\Controller\ChartsController
        arguments: ['@statistic.doctrine.service.record']
        calls:
            - [setContainer, ['@service_container']]
            - [addFilterFormClass, [{name: pie, class: "%client.filter.form.charts.class%"}]]
#    		- [addFilterFormClass, ['@?']]