services:
    client.factory.event_command_factory:
        class: ClientBundle\Factory\EventCommandFactory
        arguments:
            - "@service_container"

    client.logger.console_logger:
        class: ClientBundle\Logger\ConsoleLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: command }

